name: Kotlin CI/CD

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - keygen
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Kotlin
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build the project
      - name: Build project
        run: ./gradlew build

      # Step 5: Run tests with code coverage verification
      - name: Run tests and verify coverage
        run: ./gradlew koverVerify

      # Step 6: Generate code coverage report
      - name: Generate code coverage report
        run: ./gradlew koverHtmlReport

      # Step 7: Upload code coverage report as artifact
      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/kover/html

      - name: Publish coverage report to GitHub Pages
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: build/reports/kover/html